services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Backend'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
