version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: otica_mysql
    restart: always
    environment:
      MYSQL_DATABASE: otica_express
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  backend:
    build: . 
    container_name: otica_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/otica_express?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: